### ISSUE TITLE
copy_and_rename does copying of only files and not internal folders (no recursion)

### ISSUE THREAD

**Issue by grandkarabas** [belonesox/terrarium_assembler_win#4]
E.g. when we copy `tesseract` folder with `copy_and_rename`, the `tessdata` folder is not copied.

**Comment by grandkarabas** [comment]
Maybe it was planned?

**Comment by belonesox** [comment]
probably error. copying should be recursive.

**Comment by grandkarabas** [comment]
Resolved, so close it.
